repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: trailing-whitespace
      exclude: main_test.go
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.58.0
    hooks:
      - id: golangci-lint
  - repo: local
    hooks:
      - id: test
        name: go test
        entry: go test
        language: system
        types: [go]